### ISSUE TITLE
Odd sidekiq_1 messages

### ISSUE THREAD

**Issue by Os3r3um** [Fuzzapi/fuzzapi#63]
Hi there, 

Just wanted to give this tool a go and I started to test an endpoint. I got this one installed as a docker image because from my past experience have this Ruby mammoth configured is really a pain in the neck. 

Then I've used Burp to get a POST request and I inserted all the initial headers into the designated area, then, normally I clicked next.

So far so good but I started to get such messages:

```
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/options.rb:77:in `block (2 levels) in <class:Options>'
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/options.rb:76:in `each'
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/options.rb:76:in `each_with_object'
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/options.rb:76:in `block in <class:Options>'
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/options.rb:44:in `instance_exec'
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/options.rb:44:in `block (2 levels) in def_option'
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/options.rb:168:in `dup'
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/options.rb:44:in `block in def_option'
sidekiq_1  | /usr/local/bundle/gems/http-2.2.2/lib/http/chainable.rb:185:in `cookies'
sidekiq_1  | /usr/local/bundle/bundler/gems/API-fuzzer-ad3512d81dd2/lib/API_Fuzzer/request.rb:32:in `set_cookies_headers'
sidekiq_1  | /usr/local/bundle/bundler/gems/API-fuzzer-ad3512d81dd2/lib/API_Fuzzer/request.rb:14:in `send_api_request'
sidekiq_1  | /usr/local/bundle/bundler/gems/API-fuzzer-ad3512d81dd2/lib/API_Fuzzer.rb:36:in `static_analysis'
sidekiq_1  | /usr/local/bundle/bundler/gems/API-fuzzer-ad3512d81dd2/lib/API_Fuzzer.rb:22:in `scan'
sidekiq_1  | /app/app/workers/scan_vulnerability_worker.rb:9:in `perform'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:158:in `execute_job'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/rollbar-2.13.3/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
sidekiq_1  | /usr/local/bundle/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/logging.rb:32:in `with_context'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:174:in `stats'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:131:in `block in process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'
sidekiq_1  | /usr/local/bundle/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Any idea how to ditch such and have a trust that this testing framework actually is doing its job?

Not trying to replace my brain here, I'm just curious to evaluate it as far apparently you are putting a lotta effort into building it :)

Also, is there any switch / config to have this tool traffic through burp?

Cheers.

**Comment by lalithr95** [comment]
Thanks for giving a try, we don't have proxy developed to pull the traffic through burp and we are planning to have similar feature soon!

Regarding the stack trace, can you provide more top level stack trace? it looks like some of the top trace was truncated. That will help us understand root cause if its due to system issue or application bug.

**Comment by Os3r3um** [comment]
Right. Will get that info asap. 'Till that point, I will close this issue for the moment.
