### ISSUE TITLE
Fuzzapi not working getting  Sending failsafe response due to Errno::ECONNRESET: "Connection reset by peer - SSL_connect" and SocketError (getaddrinfo: nodename nor servname provided, or not known):   app/controllers/scans_controller.rb:61:in `create'

### ISSUE THREAD

**Issue by johnp2686** [Fuzzapi/fuzzapi#66]
I successfully configured  fuzzapi when run the api to check i am getting error

E, [2017-11-09T14:52:35.483965 #1790] ERROR -- : [Rollbar] Sending failsafe response due to Errno::ECONNRESET: "Connection reset by peer - SSL_connect" in /Users/jdomo/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': error in process_item
I, [2017-11-09T14:52:35.484038 #1790]  INFO -- : [Rollbar] Scheduling item
I, [2017-11-09T14:52:35.484141 #1790]  INFO -- : [Rollbar] Sending item
E, [2017-11-09T14:52:36.251139 #1790] ERROR -- : [Rollbar] Error processing the item: Errno::ECONNRESET, Connection reset by peer - SSL_connect. Item: {"access_token"=>"d8bb5511c8e3457cbf0a78101f257a52", "data"=>{:level=>"error", :environment=>"development", :body=>{:message=>{:body=>"Failsafe from rollbar-gem. Errno::ECONNRESET: \"Connection reset by peer - SSL_connect\" in /Users/jdomo/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': error in process_item"}}, :notifier=>{:name=>"rollbar-gem", :version=>"2.13.3"}, :custom=>{:orig_uuid=>nil, :orig_host=>nil}, :internal=>true, :failsafe=>true}}
E, [2017-11-09T14:52:36.251223 #1790] ERROR -- : [Rollbar] Error sending failsafe : Connection reset by peer - SSL_connect

SocketError (getaddrinfo: nodename nor servname provided, or not known):
  app/controllers/scans_controller.rb:61:in `create'

**Comment by johnp2686** [comment]
Anyone help me on this its very urgent

**Comment by lalithr95** [comment]
@johnp2686 this is caused because web server was not able to connect to endpoint or the target which you specified. Can you try a simple curl from the machine and see if connection works? Also would you be able to provide full stack trace which helps us to understand the root cause.
