### ISSUE TITLE
Docker setup HOWTO

### ISSUE THREAD

**Issue by sectest667** [Fuzzapi/fuzzapi#73]
Hi, just setup both fuzzAPI and redis in docker containers and thought this might help others to do the same setup as it took me some time to figure it out...

1. Clone code

`git clone https://github.com/Fuzzapi/fuzzapi.git`

2. Use redis container

`docker run -p 6379:6379 redis:alpine &`

Check what IP the docker-IP the redis service is using, eg by doing

`docker ps -f "ancestor=redis:alpine" -q | xargs docker inspect | grep -w IPAddress`

Here the result is: `"IPAddress": "172.18.0.2",` as only one redis container is running...

3. Setup fuzzapi container

Change the working directory to "fuzzAPI":
`cd fuzzapi/`

To have access to the webUI, I added a couple of entries to the whitelist:

```
$ git diff
diff --git a/config/environments/development.rb b/config/environments/development.rb
index ff73c7f..fe1793b 100644
--- a/config/environments/development.rb
+++ b/config/environments/development.rb
@@ -38,4 +38,7 @@ Rails.application.configure do
 
   # Raises error for missing translations
   # config.action_view.raise_on_missing_translations = true
+
+  # Grant access to anyone in private network and localhost
+  config.web_console.whitelisted_ips = ['127.0.0.0/8', '10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']
 end
```

Then the containers are setup by doing:
```
docker-compose build
docker-compose up

```

This step is failing for me, the containers will not start, etc, but you can get it running in the end...

This is the error message:
```
$ docker-compose up   
Pulling redis (redis:latest)...
[...]
Status: Downloaded newer image for docker.io/redis:latest
Creating fuzzapi_redis_1
Creating fuzzapi_sidekiq_1
Creating fuzzapi_web_1
Attaching to fuzzapi_redis_1, fuzzapi_sidekiq_1, fuzzapi_web_1
redis_1    | 1:C 31 Jan 15:50:45.539 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 31 Jan 15:50:45.541 # Redis version=4.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 31 Jan 15:50:45.541 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1    | 1:M 31 Jan 15:50:45.544 * Running mode=standalone, port=6379.
redis_1    | 1:M 31 Jan 15:50:45.544 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 31 Jan 15:50:45.544 # Server initialized
redis_1    | 1:M 31 Jan 15:50:45.545 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1    | 1:M 31 Jan 15:50:45.545 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1    | 1:M 31 Jan 15:50:45.545 * Ready to accept connections
sidekiq_1  | bundler: failed to load command: sidekiq (/usr/local/bundle/bin/sidekiq)
sidekiq_1  | Bundler::GemfileNotFound: /app/Gemfile not found
sidekiq_1  |   /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/definition.rb:33:in `build'
sidekiq_1  |   /usr/local/bundle/gems/bundler-1.16.1/lib/bundler.rb:135:in `definition'
sidekiq_1  |   /usr/local/bundle/gems/bundler-1.16.1/lib/bundler.rb:101:in `setup'
sidekiq_1  |   /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
sidekiq_1  |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
sidekiq_1  |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
web_1      | /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/definition.rb:33:in `build': /app/Gemfile not found (Bundler::GemfileNotFound)
web_1      | 	from /usr/local/bundle/gems/bundler-1.16.1/lib/bundler.rb:135:in `definition'
web_1      | 	from /usr/local/bundle/gems/bundler-1.16.1/lib/bundler.rb:101:in `setup'
web_1      | 	from /usr/local/bundle/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
web_1      | 	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
web_1      | 	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
fuzzapi_sidekiq_1 exited with code 1
fuzzapi_web_1 exited with code 1
```

4. Start fuzzAPI

Remember the IP from step 2 and insert it here:

`docker run -e REDIS_URL="redis://172.18.0.2:6379/0" -p 3000:3000 fuzzapi_sidekiq &`

5. WebUI is now at: http://localhost:3000

Have fun and big thanks to the project for this tool! :)

**Comment by sectest667** [comment]
The above will now work and you will have a running and functional fuzzAPI setup! :)

**Comment by abhijeth** [comment]
Thanks a lot @sectest667

**Comment by semarmendemx** [comment]
Thanks @sectest667

**Comment by kaushalk82** [comment]
hi @sectest667,

Could you please elaborate where to put this piece of code?
1. Start fuzzAPI

Remember the IP from step 2 and insert it here:

`docker run -e REDIS_URL="redis://172.18.0.2:6379/0" -p 3000:3000 fuzzapi_sidekiq &`

1. Start sidekiq

```
container=$(docker ps -f "ancestor=fuzzapi_sidekiq" -q)
docker exec -t ${container} sidekiq -v
```

Thanks a lot

**Comment by AlekKras** [comment]
> hi @sectest667,
> 
> I have done the setup and i can see all the 3 containers running. But when i am trying to access http://localhost:3000, I get connection error.
> 
> Could you please help?
> 
> Thanks a lot

Having the same issue here.

**Comment by hiba007** [comment]
replace localhost with docker ip

**Comment by katravath55** [comment]
I gave getting below error:
1. gem install pg -v '0.19.0'
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/pg-0.19.0/mkmf.log

extconf failed, exit code 1

how to resolve this?
